<a href="https://colab.research.google.com/github/assemkantayeva/assemkantayeva/blob/assemkantayeva-patch-1/II1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [2]:
alist = [1, 2, 3, 4, 5]   
narray = np.array([1, 2, 3, 4]) 

In [3]:
print(alist)
print(narray)

print(type(alist))
print(type(narray))

[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
print(narray + narray)
print(alist + alist)

[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [5]:
print(narray * 3)
print(alist * 3)

[ 3  6  9 12]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [6]:
npmatrix1 = np.array([narray, narray, narray]) 
npmatrix2 = np.array([alist, alist, alist]) 
npmatrix3 = np.array([narray, [1, 1, 1, 1], narray])

print(npmatrix1)
print(npmatrix2)
print(npmatrix3)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]]


In [7]:
# Example 1:

okmatrix = np.array([[1, 2], [3, 4]]) 
print(okmatrix)
print(okmatrix * 2)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [8]:
# Example 2:

badmatrix = np.array([[1, 2], [3, 4], [5, 6, 7]])
print(badmatrix)
print(badmatrix * 2) 

[list([1, 2]) list([3, 4]) list([5, 6, 7])]
[list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([5, 6, 7, 5, 6, 7])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  This is separate from the ipykernel package so we can avoid doing imports until


In [13]:
#Task1
result = np.array([[3, 5],[7, 9]])
print(result)

[[3 5]
 [7 9]]


In [14]:
#Task2
result1 = np.array([[1, 2], [3, 4]])
print(result1 + result1)

result2 = okmatrix - okmatrix
print(result2)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


In [17]:
#Task3
result3 = np.array([[1, 2], [3, 4]])
np.multiply(result3, result3)

array([[ 1,  4],
       [ 9, 16]])

In [18]:
#Task4
matrix3x2 = np.array([[1, 2], [3, 4], [5, 6]]) # Define a 3x2 matrix
print('Original matrix 3 x 2')
print(matrix3x2)
print('Transposed matrix 2 x 3')
print(matrix3x2.T)

Original matrix 3 x 2
[[1 2]
 [3 4]
 [5 6]]
Transposed matrix 2 x 3
[[1 3 5]
 [2 4 6]]


In [19]:
#Task5
nparray = np.array([1, 2, 3, 4]) 
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[1 2 3 4]
Transposed array
[1 2 3 4]


In [20]:
#Task6
nparray = np.array([[1, 2, 3, 4]]) 
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[[1 2 3 4]]
Transposed array
[[1]
 [2]
 [3]
 [4]]


In [26]:
#Task7
nparray1 = np.array([1, 2, 3, 4]) 
from numpy import linalg as la
norm1 = la.norm(nparray1)
nparray2 = np.array([[1, 2], [3, 4]]) 
norm2 = la.norm(nparray2)

print(norm1)
print(norm2)

5.477225575051661
5.477225575051661


In [44]:
#Task8
nparray2 = np.array([[1, 1], [2, 2], [3, 3]]) # 3 x 2 matrix. 
print(nparray2)
from numpy import linalg as la
normByCols = la.norm(nparray2, axis = (0))
normByRows = la.norm(nparray2, axis = (1))
print(normByCols)
print(normByRows)

[[1 1]
 [2 2]
 [3 3]]
[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]


In [48]:
#Task9
nparray1 = np.array([0, 1, 2, 3]) 
nparray2 = np.array([4, 5, 6, 7]) 
flavor1 = np.dot(nparray1, nparray2)  
print(flavor1)

flavor2 = np.sum(nparray1*nparray2) 
print(flavor2)

flavor3 = nparray1 @ nparray2        
print(flavor3)
           
flavor4 = 0
for a, b in zip(nparray1, nparray2):
    flavor4 += a*b  
print(flavor4)

38
38
38
38


In [49]:
norm1 = np.dot(np.array([1, 2]), np.array([3, 4])) 
norm2 = np.dot([1, 2], [3, 4]) # Dot product on python lists

print(norm1, '=', norm2 )

11 = 11


In [50]:
#Task10
nparray2 = np.array([[1, -1], [2, -2], [3, -3]]) # 3 x 2 matrix. 
sumByCols = np.sum(nparray2, axis = 0) 
sumByRows = np.sum(nparray2, axis = 1)    
print('Sum by columns: ')
print(sumByCols)
print('Sum by rows:')
print(sumByRows)

Sum by columns: 
[ 6 -6]
Sum by rows:
[0 0 0]


In [53]:
#Task11
parray2 = np.array([[1, -1], [2, -2], [3, -3]]) 
mean = np.mean(parray2)   
meanByCols = np.mean(parray2, axis = 0)  
meanByRows = np.mean(parray2, axis = 1)  
print('Matrix mean: ')
print(mean)
print('Mean by columns: ')
print(meanByCols)
print('Mean by rows:')
print(meanByRows)

Matrix mean: 
0.0
Mean by columns: 
[ 2. -2.]
Mean by rows:
[0. 0. 0.]


In [60]:
#Task12
nparray2 = np.array([[1, 1], [2, 2], [3, 3]]) # 3 x 2 matrix. 
nparrayCentered = nparray2 - np.mean(nparray2, axis = 0) #   Remove the mean for each column

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by column')
print(nparrayCentered.mean(axis=0))

Original matrix
[[1 1]
 [2 2]
 [3 3]]
Centered by columns matrix
[[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]
New mean by column
[0. 0.]


In [59]:
#Task13
nparray2 = np.array([[1, 3], [2, 4], [3, 5]]) # Define a 3 x 2 matrix. 
nparrayCentered = nparray2.T - np.mean(nparray2, axis =1) #  Remove the mean for each row
nparrayCentered = nparrayCentered.T 
### END CODE HERE ###  
print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by rows')
print(nparrayCentered.mean(axis=1))

Original matrix
[[1 3]
 [2 4]
 [3 5]]
Centered by columns matrix
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
New mean by rows
[0. 0. 0.]


In [61]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]]) # Define a 3 x 2 matrix. 

mean1 = np.mean(nparray2) # Static way
mean2 = nparray2.mean()   # Dinamic way

print(mean1, ' == ', mean2)

3.0  ==  3.0
